# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.yas_thermostat: debug

input_boolean:
  fake_heater:
  fake_cooler:
  fake_fan:

input_number:
  fake_temp:
    initial: 20.5
    min: 7
    max: 35
    step: 0.1

climate:
  - platform: yas_thermostat
    name: Test
    temp_sensor: input_number.fake_temp
    heater_switch: input_boolean.fake_heater
    cooler_switch: input_boolean.fake_cooler
    fan_switch: input_boolean.fake_fan
    default_preset: Preset2
    min_cycle: 00:00:01
    temp_step: 0.1
    preset_modes:
    - name: Preset1
      target_temp_low: 10.123
      target_temp_high: 20.455
      fan_mode: auto
    - name: Preset2
      target_temp_low: 10.123
      target_temp_high: 20.455